# Generated by Django 5.2.4 on 2025-08-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contactinfo_certificate_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
