# Generated by Django 5.2.4 on 2025-08-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_footer_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='footer_icons/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone',
            field=models.CharField(default=7982932834, max_length=20),
            preserve_default=False,
        ),
    ]
