# Generated by Django 5.2.4 on 2025-08-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_footer_email_footer_icon_footer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='icon2',
            field=models.ImageField(blank=True, null=True, upload_to='footer_icons2/'),
        ),
    ]
