# Generated by Django 5.2.4 on 2025-08-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_footer_icon2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='icon2',
            field=models.ImageField(blank=True, null=True, upload_to='footer_icons/'),
        ),
    ]
