# Generated by Django 5.2.4 on 2025-08-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_footer_icon2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='icon2',
            field=models.ImageField(blank=True, null=True, upload_to='footer_icons2/'),
        ),
    ]
