# Generated by Django 5.2.4 on 2025-08-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_footer_icon2'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='heading',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='heading2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='heading3',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
