# Generated by Django 5.2.4 on 2025-08-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_footer_heading_footer_heading2_footer_heading3'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='icon2_desc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='icon_desc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
