# Generated by Django 5.2.4 on 2025-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_footer_icon2_desc_footer_icon_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='message',
        ),
        migrations.RemoveField(
            model_name='home',
            name='name',
        ),
        migrations.AddField(
            model_name='home',
            name='Tagline',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='bigHeading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='buttonText',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='subHeading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
