# Generated by Django 5.2.4 on 2025-08-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_home_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='location',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='tagline',
        ),
        migrations.AddField(
            model_name='about',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
