# Generated by Django 5.2.4 on 2025-08-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_about_location_remove_about_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='button_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='email_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='github_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='linkedin_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='phone_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
