# Generated by Django 5.2.4 on 2025-08-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_about_button_text_about_email_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bio1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bio2',
            field=models.TextField(null=True),
        ),
    ]
