# Generated by Django 5.2.4 on 2025-08-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_about_bio1_about_bio2'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bio3',
            field=models.TextField(null=True),
        ),
    ]
