# Generated by Django 5.2.4 on 2025-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_about_bio3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='link',
        ),
        migrations.AddField(
            model_name='footer',
            name='Gitlink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='Linkdinlink',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
