# Generated by Django 5.2.4 on 2025-08-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_remove_footer_link_footer_gitlink_footer_linkdinlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='email_title',
            new_name='read',
        ),
        migrations.RemoveField(
            model_name='about',
            name='email',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone_title',
        ),
    ]
