# Generated by Django 5.2.4 on 2025-08-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_rename_email_title_about_read_remove_about_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='git_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='about',
            name='lin_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
