# Generated by Django 5.2.4 on 2025-08-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_remove_skill_level_remove_skill_name_skill_level1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='level1',
            new_name='category2',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='level2',
            new_name='four_level1',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='level3',
            new_name='four_level2',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='level4',
            new_name='four_level3',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='level5',
            new_name='four_name1',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name1',
            new_name='four_name2',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name2',
            new_name='four_name3',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='logo',
            new_name='logo1',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name3',
            new_name='one_level1',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name4',
            new_name='one_level2',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name5',
            new_name='one_level3',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='category1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='category3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='category4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='logo2',
            field=models.ImageField(blank=True, upload_to='skills/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='logo3',
            field=models.ImageField(blank=True, upload_to='skills/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='logo4',
            field=models.ImageField(blank=True, upload_to='skills/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='one_level4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='one_level5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='one_name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='one_name2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='one_name3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='one_name4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='one_name5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='three_level1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='three_level2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='three_name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='three_name2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='three_name3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='two_level1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='two_level2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='two_level3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='two_name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='two_name2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='two_name3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
