# Generated by Django 5.2.4 on 2025-08-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_rename_level1_skill_category2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='category1',
            new_name='category',
        ),
    ]
