# Generated by Django 5.2.4 on 2025-08-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_rename_category1_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, default='Frontend', max_length=100),
            preserve_default=False,
        ),
    ]
