# Generated by Django 5.2.4 on 2025-08-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='three_name3',
        ),
    ]
