# Generated by Django 5.2.4 on 2025-08-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_remove_skill_three_name3'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
