# Generated by Django 5.2.4 on 2025-08-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_skill_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('button_Text', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
