# Generated by Django 5.2.4 on 2025-08-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tagline',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
