# Generated by Django 5.2.4 on 2025-09-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_contact_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='background_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
