# Generated by Django 5.2.4 on 2025-09-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_home_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='background_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
