# Generated by Django 5.2.4 on 2025-09-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_about_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='background_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
