# Generated by Django 5.2.4 on 2025-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_skill_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='website',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='github_icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin_icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
