# Generated by Django 5.2.4 on 2025-09-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_remove_contactinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='contact_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
