# Generated by Django 5.2.4 on 2025-09-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_abouthero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
    ]
