# Generated by Django 5.2.4 on 2025-09-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_rename_end_date_experience_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
