# Generated by Django 5.2.4 on 2025-09-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_alter_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
