# Generated by Django 5.2.4 on 2025-09-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_alter_experience_date_alter_experience_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
