# Generated by Django 5.2.4 on 2025-09-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies_used',
        ),
    ]
