# Generated by Django 5.2.4 on 2025-09-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_remove_project_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('button_text', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
