# Generated by Django 5.2.4 on 2025-09-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_contactdetails_contacthero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
