# Generated by Django 5.2.4 on 2025-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_cta_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('tagline', models.TextField(blank=True)),
                ('item1', models.CharField(blank=True, max_length=50)),
                ('item2', models.CharField(blank=True, max_length=50)),
                ('item3', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
