# Generated by Django 5.2.4 on 2025-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_formdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Softskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
    ]
