# Generated by Django 5.2.4 on 2025-09-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_softskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='softskills',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=' '),
        ),
    ]
