# Generated by Django 5.2.4 on 2025-09-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_softskills_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softskills',
            name='background_image',
        ),
    ]
