# Generated by Django 5.2.4 on 2025-09-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_remove_softskills_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to=' ')),
            ],
        ),
    ]
