# Generated by Django 5.2.4 on 2025-10-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
